### ISSUE TITLE
CLI tool as a .NET Tool

### ISSUE THREAD

**Issue by alanta** [Azure/azure-functions-openapi-extension#73] opened 2021-03-18 08:22 UTC
For API Management integration, we generate OpenAPI specs at build time and push these specs to APIM during deployment.
This works very well with the CI/CD paradigm, much more so than manually importing the spec into APIM as suggested in the [APIM  integration article](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/integrate-with-apim.md). 

For WebAPI projects we use the [Swashbuckle CLI](https://www.nuget.org/packages/Swashbuckle.AspNetCore.Cli) tool which is a .net core tool and can be installed easily into an Azure DevOps pipeline agent. I'd love to have a similar solution using the CLI tool from this project for Azure Functions.

Is that in the plans? I'm willing to pitch in if that helps.

**Comment by filcole** [comment] 2021-03-18 09:02
This looks like a duplicate of #58 .

**Comment by justinyoo** [comment] 2021-03-18 23:32
@alanta Thanks for the suggestion! We DO have a CLI version of it, but it's very early stage, even in this preview.

**Comment by justinyoo** [comment] 2021-04-15 23:21
Related to: https://github.com/aliencube/AzureFunctions.Extensions/issues/132

**Comment by justinyoo** [comment] 2021-04-15 23:24
Related to: https://github.com/aliencube/AzureFunctions.Extensions/issues/126

**Comment by justinyoo** [comment] 2022-09-20 07:45
As the PR, #489, has been merged, you can generate the OpenAPI doc on-the-fly, within the GitHub Actions workflow.

**Closed** 2022-09-20 07:45 UTC
Labels: enhancement
