### ISSUE TITLE
Function Swagger UI not rendering with exception `Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http` in v1.5.0: Update

### ISSUE THREAD

**Issue by RajibLaha** [Azure/azure-functions-openapi-extension#536] opened 2023-01-10 09:21 UTC
**Describe the issue**
Added openapi support in a .net 6 isolated azure function. During opening the swagger from `http://localhost:7071/api/swagger/ui` its throwing exception `Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http`

**To Reproduce**
1. Add nuget packages "Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.0"
2. Add in Program.cs file
    .ConfigureFunctionsWorkerDefaults(worker =>
    {
        worker.UseNewtonsoftJson();
    })
    .ConfigureOpenApi();

3. Added `OpenApiOperation` attribute to functions
4. Run the application
5. Once call `http://localhost:7071/api/swagger/ui`, see error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment (please complete the following information, if applicable):**
 - OS:  Windows
 - Browser: chrome
 - Version: v1.5.0: Update

**Additional context**
- Completed stack trace are below : [2023-01-10T09:14:14.687Z] Azure Functions .NET Worker (PID: 17344) initialized in debug mode. Waiting for debugger to attach...
[2023-01-10T09:14:19.641Z] Host lock lease acquired by instance ID '0000000000000000000000001FFDC842'.
[2023-01-10T09:14:24.142Z] Executing 'Functions.RenderSwaggerUI' (Reason='This function was programmatically called via the host APIs.', Id=325d290b-bdb2-4dba-a670-c4a896a2006d)
[2023-01-10T09:14:32.755Z] Worker process started and initialized.
[2023-01-10T09:14:33.131Z] SwaggerUI page was requested.
[2023-01-10T09:14:33.201Z] Executed 'Functions.RenderSwaggerUI' (Failed, Id=325d290b-bdb2-4dba-a670-c4a896a2006d, Duration=9077ms)
[2023-01-10T09:14:33.203Z] System.Private.CoreLib: Exception while executing function: Functions.RenderSwaggerUI. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.)
[2023-01-10T09:14:33.203Z]  ---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
[2023-01-10T09:14:33.204Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Extensions.OpenApiHttpRequestDataExtensions.Queries(HttpRequestData req)
[2023-01-10T09:14:33.204Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.HttpRequestObject..ctor(HttpRequestData req)
[2023-01-10T09:14:33.205Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Functions.OpenApiTriggerFunction.RenderSwaggerUI(HttpRequestData req, FunctionContext ctx)
[2023-01-10T09:14:33.206Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.DefaultOpenApiHttpTrigger.RenderSwaggerUI(HttpRequestData req, FunctionContext ctx)
[2023-01-10T09:14:33.206Z]    --- End of inner exception stack trace ---
[2023-01-10T09:14:33.207Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-01-10T09:14:33.209Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-01-10T09:14:33.211Z]    at System.Threading.Tasks.Task`1.get_Result()
[2023-01-10T09:14:33.212Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-01-10T09:14:33.215Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-01-10T09:14:33.216Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2023-01-10T09:14:33.218Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-01-10T09:14:33.219Z] --- End of stack trace from previous location ---
[2023-01-10T09:14:33.221Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2023-01-10T09:14:33.223Z] --- End of stack trace from previous location ---
[2023-01-10T09:14:33.233Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2023-01-10T09:14:33.238Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-01-10T09:14:33.243Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 82
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-01-10T09:14:33.248Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-01-10T09:14:33.250Z]    at System.Threading.Tasks.Task`1.get_Result()
[2023-01-10T09:14:33.253Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-01-10T09:14:33.255Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-01-10T09:14:33.266Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2023-01-10T09:14:33.270Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-01-10T09:14:33.272Z] --- End of stack trace from previous location ---
[2023-01-10T09:14:33.273Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2023-01-10T09:14:33.275Z] --- End of stack trace from previous location ---
[2023-01-10T09:14:33.278Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2023-01-10T09:14:33.280Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-01-10T09:14:33.283Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 82.

**Comment by RajibLaha** [comment] 2023-01-10 10:33
Same issue also there in `[v2.0.0-preview1](https://github.com/Azure/azure-functions-openapi-extension/tree/v2.0.0-preview1)`, but downgrading to v1.4.0 is working fine

**Comment by holdenmai** [comment] 2023-01-12 18:26
I'm facing this same issue and did some investigation.  

In the solution that I encountered this (where the azure function is set up as 7.0 Isolated) it is picking up the reference to Microsoft.AspNetCore.Http from C:/Program Files/dotnet/shared/Microsoft.AspNetCore.App/7.0.0/Microsoft.AspNetCore.Http.dll

I have created several new simple projects in an attempt to replicate this, but all references to QueryCollection pull from the nuget package UNTIL either the Swashbuckle.AspNetCore.SwaggerUI or Swashbuckle.AspNetCore.SwaggerGen nuget package is added.  Upon adding this it switches over to the shared reference, upon removal switches back to the nuget reference. 

Digging further, the change comes from the Swashbuckle.AspNetCore.Swagger nuget package.  It uses the
        <frameworkReference name="Microsoft.AspNetCore.App" />
if on any targetframework but .NETStandard2.0.  
v1.4.0 didn't have this problem because it used to target .net5.0 and .net 6.0.

Not sure where the fault/fix should be performed, but it is definitely a nuisance having the nuget package version of the Microsoft.AspNetCore.Http assembly and the framework version being incompatible.

**Comment by holdenmai** [comment] 2023-01-12 18:33
In my case, the SwaggerGen project had been referenced by some legacy code changeover during migration from initial POC to actual production and has nothing to do with this project directly.

**Comment by justinyoo** [comment] 2023-01-16 04:18
@RajibLaha Thanks for the issue. Two things to confrm:

1. We don't need `.ConfigureOpenApi()` any longer from v1.5.0. Please remove this line.

```csharp
// Add in Program.cs file
.ConfigureFunctionsWorkerDefaults(worker =>
{
    worker.UseNewtonsoftJson();
})
.ConfigureOpenApi();
```

2. What version of `Microsoft.Azure.Functions.Worker` NuGet package do you use? I use v1.10.0 and it works fine with me.

Would you please double check on your end?

**Comment by justinyoo** [comment] 2023-01-16 04:22
If the issue still persists, would you please add the NuGet package, https://www.nuget.org/packages/Microsoft.AspNetCore.Http, directly on your functions app project, and let me know?

**Comment by holdenmai** [comment] 2023-01-16 20:26
@justinyoo I don't know if there is much you could do to never encounter this issue.  It is caused when the consuming project targets the Microsoft.AspNetCore.App sdk which has a different namespace for QueryCollection from the NuGet package.  

Due to this conflict being something caused by factors outside of this project, I see the following options from this team:
1. Add a .net core version of the package with the sdk as a dependency
2. Roll your own version of QueryCollection implementing the interface since the interface's namespace is standard.
3. Add code inside the OpenApiHttpRequestDataExtensions class that will pick the correct version based on what can be loaded (I would be happy to make a PR for this if desired).
4. Mark this as a known issue that can be resolved by removing other projects.

**Comment by vgool** [comment] 2023-01-17 13:53
I'm running into the same issue with 1.5.0 (and not with 1.4.0), where also for me both removing `.ConfigureOpenApi()` and adding `Microsoft.AspNetCore.Http` as a direct NuGet reference didn't help..

**Comment by vgool** [comment] 2023-01-18 08:14
I have a solution where I have some API's the "old way" and a new one as a FunctionApp, after looking deeper into this issue I found a piece of shared code which had references to `Microsoft.AspNetCore` packages.

Now that I have refactored this shared code to not have any `Microsoft.AspNetCore` references anymore, the issue is gone..

**Comment by Code-Ninja-2k** [comment] 2023-01-23 14:36
Hi, is there any progress on this issue?  The solutions above have not worked in my case.

**Comment by justinyoo** [comment] 2023-01-24 06:19
Everyone here, would you please be able to run this sample app?

https://github.com/justinyoo/azfunc-isolated-sample

I created this sample app and ran it on GitHub Codespaces (Ubuntu 20.04 LTS) with .NET 7 installed. I don't see any issue in there. I can assume that the container image used for the Codespace instance has bare minimum of .NET SDK installed.

**Comment by Code-Ninja-2k** [comment] 2023-01-24 07:00
> Everyone here, would you please be able to run this sample app?
> 
> https://github.com/justinyoo/azfunc-isolated-sample
> 
> I created this sample app and ran it on GitHub Codespaces (Ubuntu 20.04 LTS) with .NET 7 installed. I don't see any issue in there. I can assume that the container image used for the Codespace instance has bare minimum of .NET SDK installed.

I am getting a 404 on this

**Comment by RajibLaha** [comment] 2023-01-24 07:08
> Everyone here, would you please be able to run this sample app?
> 
> https://github.com/justinyoo/azfunc-isolated-sample
> 
> I created this sample app and ran it on GitHub Codespaces (Ubuntu 20.04 LTS) with .NET 7 installed. I don't see any issue in there. I can assume that the container image used for the Codespace instance has bare minimum of .NET SDK installed.

I am getting 404 too.

**Comment by justinyoo** [comment] 2023-01-24 07:34
Woops, changed it to public

**Comment by Code-Ninja-2k** [comment] 2023-01-24 08:29
I have found my issue.  My AZ uses FluentValidation which requires Microsoft.AspNetcore.App and that is causing the issue. Removing this fixes the issue - so I need to consider how to validation now!

**Closed** 2023-01-26 01:48 UTC
Labels: bug, v1.5.1
